name = "cookiecloud-worker"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[kv_namespaces]]
binding = "COOKIE_DATA"
id = "bb8c589aa4b049f4821d012cc25e2290"
preview_id = "bb8c589aa4b049f4821d012cc25e2290"

[env.production]
vars = { ENVIRONMENT = "production" }
[[env.production.kv_namespaces]]
binding = "COOKIE_DATA"
id = "bb8c589aa4b049f4821d012cc25e2290"
